#############################################################################
# Makefile for building: iSnake.app/Contents/MacOS/iSnake
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  iSnake/iSnake.pro
# Template: app
# Command: /Applications/Qt/5.13.1/clang_64/bin/qmake -o Makefile iSnake/iSnake.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -IiSnake -I. -I/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.13.1/clang_64/lib
QMAKE         = /Applications/Qt/5.13.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Applications/Qt/5.13.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Applications/Qt/5.13.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = iSnake1.0.0
DISTDIR = /Users/colin/Qt/iSnake/.tmp/iSnake1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Applications/Qt/5.13.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.13.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = iSnake/food.cpp \
		iSnake/game.cpp \
		iSnake/main.cpp \
		iSnake/mainwindow.cpp \
		iSnake/myscene.cpp \
		iSnake/obstacle.cpp \
		iSnake/parameters.cpp \
		iSnake/snake.cpp \
		iSnake/wall.cpp qrc_Resources.cpp \
		moc_game.cpp \
		moc_mainwindow.cpp \
		moc_myscene.cpp \
		moc_snake.cpp
OBJECTS       = food.o \
		game.o \
		main.o \
		mainwindow.o \
		myscene.o \
		obstacle.o \
		parameters.o \
		snake.o \
		wall.o \
		qrc_Resources.o \
		moc_game.o \
		moc_mainwindow.o \
		moc_myscene.o \
		moc_snake.o
DIST          = /Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qtquickcompiler.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/lex.prf \
		iSnake/iSnake/iSnake.pro iSnake/food.h \
		iSnake/game.h \
		iSnake/mainwindow.h \
		iSnake/myscene.h \
		iSnake/obstacle.h \
		iSnake/parameters.h \
		iSnake/snake.h \
		iSnake/wall.h iSnake/food.cpp \
		iSnake/game.cpp \
		iSnake/main.cpp \
		iSnake/mainwindow.cpp \
		iSnake/myscene.cpp \
		iSnake/obstacle.cpp \
		iSnake/parameters.cpp \
		iSnake/snake.cpp \
		iSnake/wall.cpp
QMAKE_TARGET  = iSnake
DESTDIR       = 
TARGET        = iSnake.app/Contents/MacOS/iSnake

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/colin/Qt/iSnake/iSnake/iSnake.pro


include /Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

iSnake.app/Contents/MacOS/iSnake: ui_mainwindow.h $(OBJECTS)  
	@test -d iSnake.app/Contents/MacOS/ || mkdir -p iSnake.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iSnake/iSnake.pro /Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qtquickcompiler.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.13.1/clang_64/mkspecs/features/lex.prf \
		iSnake/iSnake.pro \
		iSnake/Resources.qrc \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile iSnake/iSnake.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
/Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/toolchain.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/qtquickcompiler.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/mac.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/qmake_use.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.13.1/clang_64/mkspecs/features/lex.prf:
iSnake/iSnake.pro:
iSnake/Resources.qrc:
/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile iSnake/iSnake.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler

qmake_all: FORCE

iSnake.app/Contents/PkgInfo: 
	@test -d iSnake.app/Contents || mkdir -p iSnake.app/Contents
	@$(DEL_FILE) iSnake.app/Contents/PkgInfo
	@echo "APPL????" > iSnake.app/Contents/PkgInfo
iSnake.app/Contents/Resources/empty.lproj: 
	@test -d iSnake.app/Contents/Resources || mkdir -p iSnake.app/Contents/Resources
	@touch iSnake.app/Contents/Resources/empty.lproj
	
iSnake.app/Contents/Info.plist: 
	@test -d iSnake.app/Contents || mkdir -p iSnake.app/Contents
	@$(DEL_FILE) iSnake.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,t4.iSnake,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},t4.iSnake,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,iSnake,g" -e "s,@LIBRARY@,iSnake,g" -e "s,\$${EXECUTABLE_NAME},iSnake,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang/Info.plist.app >iSnake.app/Contents/Info.plist

all: Makefile \
		iSnake.app/Contents/PkgInfo \
		iSnake.app/Contents/Resources/empty.lproj \
		iSnake.app/Contents/Info.plist iSnake.app/Contents/MacOS/iSnake

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents iSnake/Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /Applications/Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents iSnake/food.h iSnake/game.h iSnake/mainwindow.h iSnake/myscene.h iSnake/obstacle.h iSnake/parameters.h iSnake/snake.h iSnake/wall.h $(DISTDIR)/
	$(COPY_FILE) --parents iSnake/food.cpp iSnake/game.cpp iSnake/main.cpp iSnake/mainwindow.cpp iSnake/myscene.cpp iSnake/obstacle.cpp iSnake/parameters.cpp iSnake/snake.cpp iSnake/wall.cpp $(DISTDIR)/
	$(COPY_FILE) --parents iSnake/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r iSnake.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_) -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: iSnake/Resources.qrc \
		/Applications/Qt/5.13.1/clang_64/bin/rcc \
		iSnake/icons/save.png \
		iSnake/icons/open.png \
		iSnake/icons/restart.png \
		iSnake/icons/resume.png \
		iSnake/icons/start.png \
		iSnake/icons/quit.png \
		iSnake/icons/pause.png
	/Applications/Qt/5.13.1/clang_64/bin/rcc -name Resources iSnake/Resources.qrc -o qrc_Resources.cpp

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Applications/Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /Applications/Qt/5.13.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_game.cpp moc_mainwindow.cpp moc_myscene.cpp moc_snake.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp moc_mainwindow.cpp moc_myscene.cpp moc_snake.cpp
moc_game.cpp: iSnake/game.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		moc_predefs.h \
		/Applications/Qt/5.13.1/clang_64/bin/moc
	/Applications/Qt/5.13.1/clang_64/bin/moc $(DEFINES) --include /Users/colin/Qt/iSnake/moc_predefs.h -I/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang -I/Users/colin/Qt/iSnake/iSnake -I/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/Qt/5.13.1/clang_64/lib iSnake/game.h -o moc_game.cpp

moc_mainwindow.cpp: iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		moc_predefs.h \
		/Applications/Qt/5.13.1/clang_64/bin/moc
	/Applications/Qt/5.13.1/clang_64/bin/moc $(DEFINES) --include /Users/colin/Qt/iSnake/moc_predefs.h -I/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang -I/Users/colin/Qt/iSnake/iSnake -I/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/Qt/5.13.1/clang_64/lib iSnake/mainwindow.h -o moc_mainwindow.cpp

moc_myscene.cpp: iSnake/myscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		moc_predefs.h \
		/Applications/Qt/5.13.1/clang_64/bin/moc
	/Applications/Qt/5.13.1/clang_64/bin/moc $(DEFINES) --include /Users/colin/Qt/iSnake/moc_predefs.h -I/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang -I/Users/colin/Qt/iSnake/iSnake -I/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/Qt/5.13.1/clang_64/lib iSnake/myscene.h -o moc_myscene.cpp

moc_snake.cpp: iSnake/snake.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		moc_predefs.h \
		/Applications/Qt/5.13.1/clang_64/bin/moc
	/Applications/Qt/5.13.1/clang_64/bin/moc $(DEFINES) --include /Users/colin/Qt/iSnake/moc_predefs.h -I/Applications/Qt/5.13.1/clang_64/mkspecs/macx-clang -I/Users/colin/Qt/iSnake/iSnake -I/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -F/Applications/Qt/5.13.1/clang_64/lib iSnake/snake.h -o moc_snake.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: iSnake/mainwindow.ui \
		/Applications/Qt/5.13.1/clang_64/bin/uic
	/Applications/Qt/5.13.1/clang_64/bin/uic iSnake/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

food.o: iSnake/food.cpp /Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		iSnake/food.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o food.o iSnake/food.cpp

game.o: iSnake/game.cpp /Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTime \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QEvent \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		iSnake/game.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		iSnake/myscene.h \
		iSnake/snake.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		iSnake/food.h \
		iSnake/wall.h \
		iSnake/obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o iSnake/game.cpp

main.o: iSnake/main.cpp iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o iSnake/main.cpp

mainwindow.o: iSnake/mainwindow.cpp iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		ui_mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDateTime \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		iSnake/game.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		iSnake/myscene.h \
		iSnake/snake.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		iSnake/food.h \
		iSnake/obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o iSnake/mainwindow.cpp

myscene.o: iSnake/myscene.cpp /Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		iSnake/myscene.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		iSnake/game.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myscene.o iSnake/myscene.cpp

obstacle.o: iSnake/obstacle.cpp /Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		iSnake/obstacle.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obstacle.o iSnake/obstacle.cpp

parameters.o: iSnake/parameters.cpp iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameters.o iSnake/parameters.cpp

snake.o: iSnake/snake.cpp /Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		iSnake/snake.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QSpinBox \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		iSnake/game.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QObject \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		iSnake/mainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		iSnake/food.h \
		iSnake/wall.h \
		iSnake/obstacle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snake.o iSnake/snake.cpp

wall.o: iSnake/wall.cpp /Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		iSnake/wall.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		/Applications/Qt/5.13.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		iSnake/parameters.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/QList \
		/Applications/Qt/5.13.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QRectF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qrect.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QPointF \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt/5.13.1/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wall.o iSnake/wall.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_myscene.o: moc_myscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myscene.o moc_myscene.cpp

moc_snake.o: moc_snake.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_snake.o moc_snake.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/iSnake/bin || mkdir -p $(INSTALL_ROOT)/opt/iSnake/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/iSnake/bin/iSnake.app
	
	-$(QINSTALL) iSnake.app $(INSTALL_ROOT)/opt/iSnake/bin/iSnake.app
	-$(STRIP) $(INSTALL_ROOT)/opt/iSnake/bin/iSnake.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/iSnake/bin/iSnake.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/iSnake/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

